#ifndef ERRORCODES_H
#define ERRORCODES_H

#include "Core/definitions.h"

const d_ERRORCODE e_NO_ERROR = 0;

const d_ERRORCODE e_STATES_COUNT_IS_NOT_VALID = 1;
const d_ERRORCODE e_PROBABILITIES_SUM_IS_NOT_1 = 2;
const d_ERRORCODE e_PROBABILITY_IS_LESS_THAN_0 = 3;
const d_ERRORCODE e_PROBABILITY_IS_GREATER_THAN_1 = 4;
const d_ERRORCODE e_COMPONENT_STATE_IS_INVALID = 5;
const d_ERRORCODE e_SYSTEM_STATE_IS_INVALID = 6;
const d_ERRORCODE e_COMPONENT_NOT_EXISTS = 7;
const d_ERRORCODE e_PROBABILITY_IS_NOT_SET = 8;
const d_ERRORCODE e_IMPORTANCE_INDEX_IS_NOT_DEFINED = 9;
const d_ERRORCODE e_SYSTEM_STATES_COUNT_IS_DIFFERENT = 10;
const d_ERRORCODE e_COMPONENT_STATES_COUNT_IS_DIFFERENT = 11;
const d_ERRORCODE e_INDEX_IS_NOT_COMPUTED = 12;
const d_ERRORCODE e_SYSTEM_IS_NOT_INIT = 13;
const d_ERRORCODE e_INDICESMATRIX_IS_NOT_CREATED = 14;
const d_ERRORCODE e_DPLR_PROBLEM = 15;

const d_ERRORCODE e_COMPONENTS_COUNT_IS_NOT_POSITIVE_NUMBER = 16;
const d_ERRORCODE e_SYSTEM_CONFIGURATIONS_COUNT_LIMIT_EXCEEDED = 17;
const d_ERRORCODE e_COMPONENT_ALREADY_EXISTS = 18;
const d_ERRORCODE e_REACH_EOF = 19;
const d_ERRORCODE e_BAD_VALUE = 20;
const d_ERRORCODE e_PROBABILITIES_COUNT_IS_DIFEERENT_FROM_STATES_COUNT = 21;
const d_ERRORCODE e_COMPONENT_ID_OVERFLOW = 22;
const d_ERRORCODE e_COMPONENTS_COUNT_IS_INVALID = 23;
const d_ERRORCODE e_STRUCTURAL_FUNCTION_IS_NOT_UPDATED = 24;


const d_ERRORCODE e_FILE_NOT_FOUND = 100;
const d_ERRORCODE e_FILE_HAS_WRONG_FORMAT = 101;

#endif // ERRORCODES_H
